[tool.poetry]
name = "myhealth"
version = "0.1.0"
description = ""
authors = ["shanemarvinmay <shanemarvinmay@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
